"""add columns to table

Revision ID: 122c2797225d
Revises: 
Create Date: 2024-07-01 22:09:18.064708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122c2797225d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
